dist: xenial
language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - PACKAGE=permutations
    - PINS="algebra:git+https://github.com/ghuysmans/algebra/ dot:git+https://github.com/ghuysmans/ocamldot/"
  matrix:
    - OCAML_VERSION=4.07
    - OCAML_VERSION=4.08
    - OCAML_VERSION=4.09
    - OCAML_VERSION=4.10
os:
  - linux
